### ISSUE TITLE
Inconsistent use of indestructible nodes in "Plain Battle"

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/maps#50]
The team-bases in the original Plain Battle were made up of `default:stonebrick`, but the recent enhancement commit 55e623179f31d449fde3d4c083f78f3df914b15f threw indestructible nodes in the mix. The result is that the extra improvements to the bases are indestructible while the base itself is destructible.

@JostP: Bringing this to your attention.

**Comment by JostP** [comment]
What do you mean with "team-bases", maybe wall around bases?

If yes (for wall) than this isn't something what I don't know. I planned this when I was making map. I put indestructible nodes there to prevent enemy players to enter into "defence corridor". 

But I see that players don't use "defence corridor", because it is quite useless and I will improve it and include changes in #43 as it hasn't been merged yet. I can use destructable nodes if you want, maybe this is better idea

**Comment by ClobberXD** [comment]
Using indestructible nodes for fortifying the "defence corridor" is fine. The problem is that the original parts of the base are still destructible. This means that one could simply enter the defence corridor from above by breaking the nodes on top. The problem is that the indestructible nodes serve no real purpose, as they're mixed with destructible nodes.
